---
output: html_document
---
# The Problem

In the recent years we observed arise of several R packages enhancing the process of writing R code. R programmers can now easily incorporate best programmer practices during the development of new tools. On the other hand, we see only a little improvement in the area of R tools designed to aid during the analysis of the data. Our aim is to create a new package responsible for managing the workflow of data analysis, from data pre-processing till reporting. 

## Key functionalities of the package

2. Isolating the workspace of the workflow (i.e. not by loading all packages, but only specific functions). 
1. Documenting and testing functions written for the purpose of an analysis.
1. Documenting data sets and reports.
2. Tracking the workflow - which functions, data sets are employed in the specific module of the analysis, what is the output of a module.
3. Caching results of the time-consuming procedures to speed up reiterating the workflow.
4. Preserving the past versions of the workflow.

## Similar projects

The functionalities helpful in the management data analysis are scattered among several packages, but only one package, [ProjectTemplate](http://projecttemplate.net/), aims directly to solve this problem. Nevertheless, our project cannot be perceived as a counterpart of *ProjectTemplate*, because we will focus on different aspects of the workflow management

## Methods

Instead of inventing wheel from the scratch, we want to reuse functionalities already present in several other packages, but streamline their usage to direct improvements of the workflow management in R.

# Overview

An analysis is never done in a single step. Instead, it is more complicated process, requiring moving back and forward, sometimes even drastic changes in a scope or a goal of the study. Our project will be focused on preserving these intermediate steps of formulating a final analysis workflow streamlining the return to previous solutions. 

The next problem of any analytic workflow is the management of the code involved in the analysis employing often both functions from several packages and written specifically for the purpose of the current task. The former may create a namespace cluttered with many masked objects, the latter involves dealing with the untested code. We will provide users with the functionalities to keep the analysis environment clean and to both test and document their own code.


## Detailed description of the project

### Idea of workflow unit

The workflow is divided by the user into abstract units (functions or expressions). Each unit must specified input (data set provided in the worflow or output of other unit) and output.

### Isolating the workspace of the workflow

After loading several packages into to namespace, users often encounters that some functions were masked by other. Such behavior either imposes loading packages in a very specific order or the usage of double colon operators. Both possible solutions are inconvenient to use. **reporteR** will  add functions from the specific packages to the new environment, essentially creating the new namespace for the workflow.  

This functionality might be further refined by incorporating [packrat](https://cran.r-project.org/package=packrat) to load functions only from the library adjusted for a given workflow.  

### Documenting and testing functions written for the purpose of an analysis

The written on the fly functions tend to have much lower quality that functions coming from packages. The burden of writing proper documentation and argument checks may seem unnecessary for the custom functions used in the analysis. **reporteR** supports analysts by generating documentation for functions written using the roxygen standard.

Written functions will be easily and elegantly loaded via [modules](https://github.com/klmr/modules) package without cluttering the global namespace, but at the same time staying fully accessible. 

### Documenting data sets and reports.

Sources of metadata for data sets and reports:  
1. abstr field in the yaml preamble of rmd reports.  
2. .rnw.  
3. data.  

### Tracking the workflow

Management of larger workflows might be hard without any symbolic representation. On the other hand, diagrams, aside from their utility, may not represent accurately the current state of the workflow. **reporteR** will create a symbolic scheme of the workflow drawing relationships between particular workflow units. The automatically created diagram might be expertet in [mermaid](https://github.com/knsv/mermaid) format and further refined.

Call stack + similar to [profvis](https://github.com/rstudio/profvis).

### Caching results

Some units of the workflow may be too time consuming to be evaluated during reruns of the workflow. **reporteR** will automatically take care of it. The package will measure time required for each workflow unit and stash such objects, that requires more time than indicates threshold set by the user. Workflow units will be recalculated only if their content

### Preserving the past versions of the workflow

git tag + archivist.
